### ISSUE TITLE
HTTP 400 – Bad Request – yii\web\HttpException Invalid formatter

### ISSUE THREAD

**Issue by stevenvandemoortele** [FosterCommerce/commerceinsights#2]
Error when trying to access /commerceinsights/customers and /commerceinsights/products route in plugin.

```
yii\web\HttpException: Invalid formatter in /var/www/vanomobilshop.test/vendor/fostercommerce/commerceinsights/src/formatters/BaseFormatter.php:63
Stack trace:
#0 /var/www/vanomobilshop.test/vendor/fostercommerce/commerceinsights/src/controllers/ProductController.php(54): fostercommerce\commerceinsights\formatters\BaseFormatter::getFormatter(NULL)
#1 [internal function]: fostercommerce\commerceinsights\controllers\ProductController->actionProductIndex('html')
#2 /var/www/vanomobilshop.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/vanomobilshop.test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/vanomobilshop.test/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('product-index', Array)
#5 /var/www/vanomobilshop.test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('product-index', Array)
#6 /var/www/vanomobilshop.test/vendor/craftcms/cms/src/web/Application.php(284): yii\base\Module->runAction('commerceinsight...', Array)
#7 /var/www/vanomobilshop.test/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('commerceinsight...', Array)
#8 /var/www/vanomobilshop.test/vendor/craftcms/cms/src/web/Application.php(273): yii\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/vanomobilshop.test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /var/www/vanomobilshop.test/public/index.php(21): yii\base\Application->run()
#11 {main} ```

**Comment by johnnynotsolucky** [comment]
@stevenvandemoortele This has been resolved with the [1.0.0-beta.12](https://github.com/FosterCommerce/commerceinsights/releases/tag/1.0.0-beta.12) release.

The /customers and /products routes have been removed in this version.
