### ISSUE TITLE
Twig Runtime Error when accessing /orders and /revenue links

### ISSUE THREAD

**Issue by michtio** [FosterCommerce/commerceinsights#3]
This is on Craft 3.1.14 whenever I try to go to Orders or Revenue I get the following error:

`Impossible to invoke a method ("format") on a string variable ("2019-02-15T13:51:21")`

Stacktrace:

```
Twig_Error_Runtime: Impossible to invoke a method ("format") on a string variable ("2019-02-15T13:51:22"). in /var/www/bloom.test/vendor/craftcms/cms/src/templates/_includes/forms/date.html:22
Stack trace:
#0 /var/www/bloom.test/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), '2019-02-15T13:5...', 'format', Array, 'method', false, false)
#1 /var/www/bloom.test/storage/runtime/compiled_templates/77/776db29f948111536ec9d3e38fb9af1a904bc6a443edc07695e76d180a70b93e.php(63): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), '2019-02-15T13:5...', 'format', Array, 'method')
#2 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_630fd4a5c37b8d3f35c64113c32b8ee6fa72c25705f3a8ce764fbaccbb907dc7->doDisplay(Array, Array)
#3 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#4 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#6 /var/www/bloom.test/storage/runtime/compiled_templates/b3/b3eea2e029a44b82b68c1aafdf15cf2440dbd2819893fc582d5b8a8556c6afbc.php(78): craft\web\twig\Template->display(Array)
#7 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_a4dffad999ff917bf242248456579481d0ca56f9dbadfefb11bc8c7f385a8912->block_actionButton(Array, Array)
#8 /var/www/bloom.test/storage/runtime/compiled_templates/88/8862d6f4cac4222afb1d294585ff73cdb1a6e85194b0a6e0c700f866ae6cf56a.php(575): Twig_Template->displayBlock('actionButton', Array, Array)
#9 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_58de459e05287d93808b1eb5d4cf4065538ab147b3e977734439a154bfadd343->block_header(Array, Array)
#10 /var/www/bloom.test/storage/runtime/compiled_templates/88/8862d6f4cac4222afb1d294585ff73cdb1a6e85194b0a6e0c700f866ae6cf56a.php(516): Twig_Template->displayBlock('header', Array, Array)
#11 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_58de459e05287d93808b1eb5d4cf4065538ab147b3e977734439a154bfadd343->block_body(Array, Array)
#12 /var/www/bloom.test/storage/runtime/compiled_templates/64/6409c5b739c926ae6b9ebb34558990f06e3b22676dffec6367572dfa84c4d404.php(60): Twig_Template->displayBlock('body', Array, Array)
#13 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_28b00cf7eda9d29411a02fe78ff12cfbc1c69609d4b65e13c8dafb03de73d993->doDisplay(Array, Array)
#14 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#15 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#17 /var/www/bloom.test/storage/runtime/compiled_templates/0d/0d0ef1113f29ec4076820fd00934ab65823a0519dc24fa66f58655111ef3ddde.php(40): craft\web\twig\Template->display(Array, Array)
#18 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_e545db384e5db3f293d2830c9034d157e099d525fa2f5ff4353cd972f9819ba4->doDisplay(Array, Array)
#19 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#20 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#22 /var/www/bloom.test/storage/runtime/compiled_templates/88/8862d6f4cac4222afb1d294585ff73cdb1a6e85194b0a6e0c700f866ae6cf56a.php(95): craft\web\twig\Template->display(Array, Array)
#23 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_58de459e05287d93808b1eb5d4cf4065538ab147b3e977734439a154bfadd343->doDisplay(Array, Array)
#24 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#25 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#26 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#27 /var/www/bloom.test/storage/runtime/compiled_templates/b3/b3eea2e029a44b82b68c1aafdf15cf2440dbd2819893fc582d5b8a8556c6afbc.php(39): craft\web\twig\Template->display(Array, Array)
#28 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_a4dffad999ff917bf242248456579481d0ca56f9dbadfefb11bc8c7f385a8912->doDisplay(Array, Array)
#29 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#30 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#31 /var/www/bloom.test/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#32 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#33 /var/www/bloom.test/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#34 /var/www/bloom.test/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('commerceinsight...', Array)
#35 /var/www/bloom.test/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('commerceinsight...', Array)
#36 /var/www/bloom.test/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('commerceinsight...', Array)
#37 /var/www/bloom.test/vendor/fostercommerce/commerceinsights/src/controllers/RevenueController.php(75): craft\web\Controller->renderTemplate('commerceinsight...', Array)
#38 [internal function]: fostercommerce\commerceinsights\controllers\RevenueController->actionRevenueIndex('html')
#39 /var/www/bloom.test/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#40 /var/www/bloom.test/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#41 /var/www/bloom.test/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('revenue-index', Array)
#42 /var/www/bloom.test/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('revenue-index', Array)
#43 /var/www/bloom.test/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('commerceinsight...', Array)
#44 /var/www/bloom.test/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('commerceinsight...', Array)
#45 /var/www/bloom.test/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#46 /var/www/bloom.test/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#47 /var/www/bloom.test/public/index.php(21): yii\base\Application->run()
#48 {main}
```

**Comment by johnnynotsolucky** [comment]
@michtio This has been resolved with the [1.0.0-beta.12](https://github.com/FosterCommerce/commerceinsights/releases/tag/1.0.0-beta.12) release.
